# MySQL.  Versions 4.1 and 5.0 are recommended.
common: &common
  adapter: mysql
  host: 127.0.0.1
  username: root
  password:
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: checkers_dev

test: &test
  <<: *common
  database: checkers_test